# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('administrators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('title', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=80)),
                ('alternative_1', models.CharField(max_length=20)),
                ('alternative_2', models.CharField(max_length=20)),
                ('alternative_3', models.CharField(max_length=20)),
                ('alternative_4', models.CharField(max_length=20)),
                ('correct_alternative', models.IntegerField(choices=[(1, 'Alternative 1'), (2, 'Alternative 2'), (3, 'Alternative 3'), (4, 'Alternative 4')], default=1)),
                ('is_worth', models.IntegerField()),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingMaterial',
            fields=[
                ('title', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultVal', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeTag',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('material', models.ManyToManyField(to='quiz.ReadingMaterial')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='themeTags',
            field=models.ManyToManyField(to='quiz.ThemeTag'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='contains',
            field=models.ManyToManyField(to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.ManyToManyField(to='quiz.ReadingMaterial'),
        ),
    ]
