# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='administrators',
            field=models.ManyToManyField(related_name='administrated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
