# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('quiz', '0002_auto_20170308_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCollection',
            fields=[
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AlterField(
            model_name='course',
            name='administrators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursecollection',
            name='courses',
            field=models.ManyToManyField(to='quiz.Course'),
        ),
    ]
